export const cities = [
    { name: "القاهرة", value: "Cairo" },
    { name: "الاسكندرية", value: "Alexandria" },
    { name: "الجيزة", value: "Giza" },
    { name: "المنصورة", value: "Mansoura" },
    { name: "أسوان", value: "Aswan" },
    { name: "قنا", value: "Qena" },
    { name: "الأقصر", value: "Luxor" },
    { name: "القليوبية", value: "Qalyubia" },
    { name: "الشرقية", value: "Sharqia" },
    { name: "الدقهلية", value: "Dakahlia" },
    { name: "البحيرة", value: "Beheira" },
    { name: "المنيا", value: "Minya" },
    { name: "المنوفية", value: "Menoufia" },
    { name: "الغربية", value: "Gharbia" },
    { name: "الفيوم", value: "Fayoum" },
    { name: "أسيوط", value: "Asyut" },
    { name: "سوهاج", value: "Sohag" },
    { name: "بني سويف", value: "Beni Suef" },
    { name: "كفر الشيخ", value: "Kafr El Sheikh" },
    { name: "الاسماعيلية", value: "Ismailia" },
    { name: "دمياط", value: "Damietta" },
    { name: "بورسعيد", value: "Port Said" },
    { name: "السويس", value: "Suez" },
    { name: "البحر الاحمر", value: "Red Sea" },
    { name: "الوادي الجديد", value: "New Valley" },
    { name: "مطروح", value: "Matrouh" },
    { name: "شمال سيناء", value: "North Sinai" },
    { name: "جنوب سيناء", value: "South Sinai" },
]